version: "3"

volumes:
  db-data:
    driver: local

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
